name: Deploy To Tencent Server

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [ main ]
  # 手动触发部署
  workflow_dispatch:

env:
  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  SERVER_USER_NAME: ${{ secrets.SERVER_USER_NAME }} # 服务器用户名

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: '16.15.0'

      # 当前目录
      - name: Address docs root directory
        run: ls -l

      # 缓存 node_modules
      - name: Cache dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      # 运行构建脚本
      - name: Build VuePress site
        run: npm run build

      # 上传
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ env.SERVER_PRIVATE_KEY }}

      # 使用 ssh-keyscan 命令扫描我们服务器的公钥并保存到github actions虚拟环境的 ~/.ssh/known_hosts 中，用于工作流的无人值守
      - name: Scan public keys
        run: ssh-keyscan ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      # 部署 通过rsync将虚拟环境下编译好的目录同步到我们的服务器指定目录下。rsync --delete会删除目的目录中不在源目录中的文件。
      - name: Deploy
        run: rsync -av --delete docs root@${{ secrets.SERVER_HOST }}:/usr/local/nginx/html